#!/bin/bash
#
# mysql insert Script
#
###################################################

#echo mysql -e select * from users;

password="***"

echo "insert into androidDB.videoTBL values('test1', 'test1');" | mysql -u"root" -p$password



